### PR TITLE
add sz_auto, and test it locally

### PR DESCRIPTION
**Pull request by Real-Chen-usc**
Hello Robert,
I have added sz_auto plugin to libpressio. I have tested locally, which seems fine. 
However, since I did not have control over sz_auto repo, there are some issues:
1. The version info in the plugin is not correct, since I don't have access to their version. I will ask Di to get their version info. 
2. In their of CMakeLists, they did not export the whole project. Therefore, I cannot use find_package() to link the library. I can only link it by hand. I will also ask Di to maybe update their CMakeLists.

### CODE REVIEW

**Comment by robertu94** [comment]
@Real-Chen-usc I did a cursory examination and I have a few thoughts:

>  1. The version info in the plugin is not correct, since I don't have access to their version. I will ask Di to get their version info.
>   2.  In their of CMakeLists, they did not export the whole project. Therefore, I cannot use find_package() to link the library. I can only link it by hand. I will also ask Di to maybe update their CMakeLists.

Yes, we should wait for these things;  I think they can do these quickly.

I have a few more questions/comments:

1. Could you please point me to where I can download SZ_Auto?  Everything else in libpressio is installable via spack.  I will want to do the same for SZ_Auto.
2. Does SZ_Auto have the notion of an error bound mode? and/or any other settings set via global variables?  If it does we should export these via `get_options` and `set_options`.
3. Does SZ_Auto depend on SZ?  If so we need to document that, and make some changes to the cmake options to make them dependent options.  Additionally this means that SZ_Auto does not implement pressio_thread_safety_multiple since the global variables would make it non-thread safe.
4. Please add some documentation to the `README` and to `docs/PressioOptions.md` about the options for the compressor

I'll do a more careful review and test it for myself when @disheng222  gets the Cmake and version information issues fixed.

**Comment by Real-Chen-usc** [comment]
1. You can download via git clone https://github.com/lxAltria/meta_compressor.git. You should checkout autotuning branch before installing. 
2. As far as I know, they only have error bounds. However, I am not sure about that, and I will check with Di. 
3. No, sz_auto can be run independently. They only depend on zstd.

**Comment by Real-Chen-usc** [comment]
Hello Robert, 
I have contact with the author of SZauto, and he added the version information as well as updated his CMake file so that we can directly use find_package in the CMakelists to install. Also, the author has made an independent repository so that we don't need to check out a specific branch. https://github.com/szcompressor/SZauto

Let me know if you have any questions.

**Comment by robertu94** [comment]
Looks good to me, I'll merge this soon.

**Comment by robertu94** [comment]
merged in `a5e40c0e4effffc0b89b6ddbb7cee8eefef59639`

**Pull request closed without merging**
